### ISSUE TITLE
Which syntax use to refer to another content

### ISSUE THREAD

**Issue by NicolasLopes7** [learning-in-public/learn-you-computer-science#4]
Vote below in your favorite syntax to refer to another content:

👍  - `#[]()`
😄  - `{}()`
🎉  - `[[][]]`
🚀  - `[]{}`

**Comment by lffg** [comment]
I have concerns with a possible ambiguity while parsing intra-links with the `#[]()` syntax. Maybe if the can use a custom hook _before_ parsing that'd be feasible.

I would vote for a syntax which is easy to type and has no similarities with any existing markdown link syntax, such as 2, 3 or 4.
